
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Run NGINX container
  docker_container:
    name: nginx_web
    image: nginx:latest
    state: started
    ports:
      - "8080:80"
